image: gxodocker/active-citizen-dockerhub-repo:node-angular11

variables:
  APP_NAME: active-citizen
  ENV_NAME: active-citizen-dev

stages:
  - build
  - test
  - deploy

building the app:
  stage: build
  script:
    - ng --version
    - npm --version
    - npm install
    - ng build --prod
  artifacts:
    paths:
      - ./dist

testing the app:
  stage: test
  script:
    - npm install
    - ng test --watch=false

deploy to staging:
  stage: deploy
  image: heroku/heroku:20
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=active-citizen-staging --api-key=$HEROKU_API_KEY
  only:
    - master


