image: alpine

variables:
  S3_BUCKET: "active-citizen-deployment"

stages:
  - build
#  - test
  - deploy

build:
  stage: build
  script:
    - apk add --update nodejs nodejs-npm
    - npm i -g @angular/cli
    - ng --version
    - npm install --save-dev @angular-devkit/build-angular
    - ng build
  artifacts:
    paths:
      - ./dist

#test:
#  stage: test
#  script:
#    - apk add --update nodejs nodejs-npm
#    - npm i -g @angular/cli
#    - ng --version
#    - npm install --save-dev @angular-devkit/build-angular
#    - npm install
#    - ng test --browsers ChromeHeadlessNoSandbox --watch=false

deploy:
  stage: deploy
  image:
    name: banst/awscli
    entrypoint: [""]
  script:
    - ls
    - aws configure set region us-east-1
    - aws s3 cp dist s3://$S3_BUCKET/


