stages:
  - build
  - test
#  - deploy

build:
  stage: build
  image: alpine
  script:
    - apk add --update nodejs nodejs-npm
    - npm i -g @angular/cli
    - ng --version
    - npm install --save-dev @angular-devkit/build-angular
    - ng build
  artifacts:
    paths:
      - ./dist

test:
  stage: test
  image: alpine
  script:
    - apk add --update nodejs nodejs-npm
    - npm i -g @angular/cli
    - ng --version
    - npm install --save-dev @angular-devkit/build-angular
    - npm install
    - ng test

#deploy:
#  stage: deploy
#  image:
#    name: banst/awscli
#    entrypoint: [""]
#  script:
#    - aws configure set region us-east-1
#    - aws s3 cp ./build/libs/cars-api.jar s3://$S3_BUCKET/cars-api.jar
