image: alpine

variables:
  S3_BUCKET: "active-citizen-deployment"

#stages:
#  - build
#  - test
#  - deploy

stages:
  - test

#build:
#  stage: build
#  script:
#    - apk add --update nodejs nodejs-npm
#    - npm i -g @angular/cli
#    - ng --version
#    - npm install --save-dev @angular-devkit/build-angular
#    - ng build
#  artifacts:
#    paths:
#      - ./dist

test:
  stage: test
  script:
    - echo "AWS_ACCESS_KEY_ID"

#deploy:
#  stage: deploy
#  image:
#    name: banst/awscli
#    entrypoint: [""]
#  script:
#    - aws configure set aws_access_key_id AWS_ACCESS_KEY_ID
#    - aws configure set aws_secret_access_key AWS_SECRET_ACCESS_KEY
#    - aws configure set region us-east-1
#    - aws configure list
#    - aws s3 cp dist s3://$S3_BUCKET/ --recursive


