image: gxodocker/active-citizen-dockerhub-repo:node-angular11

variables:
  APP_NAME: active-citizen
  ENV_NAME: active-citizen-dev

stages:
#  - build
#  - test
  - deploy

#build:
#  stage: build
#  script:
#    - ng --version
#    - npm --version
#    - npm install
#    - ng build --prod
#  artifacts:
#    paths:
#      - ./dist
#
#test:
#  stage: test
#  script:
#    - npm install
#    - ng test --watch=false

#deploy:
#  stage: deploy
#  image:
#    name: banst/awscli
#    entrypoint: [""]
#  script:
#    - apk add git
#    - git config --global user.email $AWS_USER_EMAIL
#    - git config --global user.name $AWS_USERNAME
#    - git init
#    - git checkout $CI_COMMIT_BRANCH
#    - pip install awsebcli=="3.14.8"
#    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
#    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
#    - aws configure set region us-east-1
#    - aws s3 rm s3://$S3_BUCKET/$APP_NAME --recursive
#    - eb deploy $ENV_NAME --timeout 30

deploy:
  stage: deploy
  image: heroku/heroku:20
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - heroku config:set NODE_BUILD_FLAGS="--stag"
    - dpl --provider=heroku --app=active-citizen-staging --api-key=$HEROKU_API_KEY


