image: alpine

variables:
  APP_NAME: active-citizen
  ENV_NAME: active-citizen-dev
  BUCKET_NAME: active-citizen-bucket

stages:
  #  - build
  #  - test
  - deploy

#build:
#  stage: build
#  script:
#    - apk add --update nodejs nodejs-npm
#    - npm i -g @angular/cli
#    - ng --version
#    - npm install --save-dev @angular-devkit/build-angular
#    - ng build --prod
#  artifacts:
#    paths:
#      - ./dist

#test:
#  stage: test
#  script:
#    - apk add --update nodejs nodejs-npm
#    - npm i -g @angular/cli
#    - ng --version
#    - npm install --save-dev @angular-devkit/build-angular
#    - npm install
#    - ng test --browsers ChromeHeadlessNoSandbox --watch=false

deploy:
  stage: deploy
  image:
    name: banst/awscli
    entrypoint: [""]
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region us-east-1
    - aws configure list
    - aws s3 rm s3://$S3_BUCKET/active-citizen --recursive
    - ls
    - aws s3 cp ./ s3://$S3_BUCKET/$BUCKET_NAME --recursive
    - aws elasticbeanstalk create-application-version --application-name $APP_NAME --source-bundle S3Bucket=$S3_BUCKET,S3Key=$BUCKET_NAME --version-label "app-3e93-201011_172302"
    - aws elasticbeanstalk update-environment --application-name $APP_NAME --environment-name $ENV_NAME --version-label "app-3e93-201011_172302"


